package com.arghamnegargroup.core.features.core.data.remote

object NetworkConstants {
    const val RETRY = 3
    const val TIMEOUT: Long = 30
    const val UNKNOWN_ERROR = "خطایی رخ داده است."

}